export type Kiko = { name: string; id: string };

export const KIKOS: Kiko[] = [
  { name: "Chocolate", id: "bjlkdzbd" },
  { name: "Woodland", id: "8jtxbfcn" },
  { name: "Coconut", id: "oqbqkqzt" },
  { name: "Burlap", id: "t3vmfjfk" },
  { name: "Brown", id: "3xcc8hov" },
  { name: "Clay", id: "85434s2d" },
  { name: "Biscuit", id: "g7vmr29b" },
  { name: "Tyrannian", id: "h5mvov89" },
  { name: "Desert", id: "7qhcgn5t" },
  { name: "Spotted", id: "lmq9b7fm" },
  { name: "Yellow", id: "86b5xdn6" },
  { name: "Gold", id: "9574wtso" },
  { name: "Dimensional", id: "wsxrbt2o" },
  { name: "Jelly", id: "bzgqmjqx" },
  { name: "Halloween", id: "zqqw7b4k" },
  { name: "Orange", id: "4zzvg8tk" },
  { name: "Split", id: "62zgorg2" },
  { name: "Faerie", id: "3v73mndv" },
  { name: "Purple", id: "q4twbdvv" },
  { name: "Darigan", id: "4k3bzdfg" },
  { name: "Wraith", id: "994wkgrr" },
  { name: "Magma", id: "8l22mlq6" },
  { name: "Fire", id: "3mtw9t7v" },
  { name: "Shadow", id: "3vwbj6j4" },
  { name: "Skunk", id: "mkfd65rx" },
  { name: "Grey", id: "dvd5tlcq" },
  { name: "Mutant", id: "wdqnjz2z" },
  { name: "Pirate", id: "dw2htn56" },
  { name: "Blue", id: "2qlfqqnd" },
  { name: "Camouflage", id: "cmk2z23z" },
  { name: "Chokato", id: "sn2bs92v" },
  { name: "Starry", id: "7g8s7rqx" },
  { name: "Electric", id: "gmn6xcxq" },
  { name: "Speckled", id: "bs8t6hg8" },
  { name: "Glowing", id: "3jv86g46" },
  { name: "Green", id: "42j5q3zx" },
  { name: "Disco", id: "4xz6rrlc" },
  { name: "Snot", id: "s4otvn9o" },
  { name: "Swamp Gas", id: "gbkrxomz" },
  { name: "Zombie", id: "9fddr3zk" },
  { name: "Transparent", id: "bgr3ogwg" },
  { name: "Silver", id: "5kt4x25k" },
  { name: "Sketch", id: "wbn7tg9x" },
  { name: "Snow", id: "mxdtz58l" },
  { name: "Island", id: "djb6zmgn" },
  { name: "White", id: "w28243zz" },
  { name: "Christmas", id: "xr789o9d" },
  { name: "Robot", id: "nnbxjr42" },
  { name: "Royal Boy", id: "xbgv8qtq" },
  { name: "Garlic", id: "o958d3rt" },
  { name: "Custard", id: "n6wwcfz3" },
  { name: "Sponge", id: "lw89wdh9" },
  { name: "Candy", id: "nv4ww9or" },
  { name: "Royal Girl", id: "h436tohx" },
  { name: "Plushie", id: "f386j6xk" },
  { name: "Pink", id: "bmvtwmow" },
  { name: "Cloud", id: "5gf3r525" },
  { name: "Striped", id: "lgwjq46o" },
  { name: "Pastel", id: "9hqrzn3h" },
  { name: "Baby", id: "d54hfwc7" },
  { name: "Toy", id: "kfm2kdxr" },
  { name: "Ghost", id: "fjx8c3ro" },
  { name: "Marble", id: "7crcclt5" },
  { name: "Mosaic", id: "mqlor325" },
  { name: "Eventide", id: "4r5mq8zq" },
  { name: "Rainbow", id: "vf39q8x4" },
  { name: "Strawberry", id: "cj7z3dc5" },
  { name: "Checkered", id: "6hn8qq86" },
];

export const kikoImage = (id: string) => `https://pets.neopets.com/cp/${id}/1/3.png`;
